# Model parameters
model:
  # Linear model architecture
  ln_model: [True]  # Use a linear model or not.
  ln_epochs: [100]  # Linear model epochs
  ln_lr: [1.e-2]  # Linear model Learning rate
  # CNN architecture
  cnn_model: ['efficientnet_b3']  # Choice of CNN model
  cnn_lr: [1.e-4]  # CNN model learning rate
  cnn_dp: [0.75]  # CNN model dropout rate
  cnn_epochs: [100]  # CNN model epochs.
  # Hybrid model architecture
  hybrid_loop: [True]  # Use a linear model or not.
  # General training parameters
  epochs: [250]  # If the model is not hybrid, use this value
  lr: [1.e-4]  # If the model is not hybrid, use this value
  seed: [3110]  # Seed used for training
  # Training, validation, testing and holdout split
  val_months: [[2, 3]]  # Month used for validation
  test_months: [[11, 12]]  # Month used for testing
  holdout_months: [[1, 10]]  # Month used for holdout
  # wl: # Wavelengths used as input
  "94": [[0]]  
  "131": [[1]]  
  "171": [[2]]  
  "193": [[3]]  
  "211": [[4]]  
  "304": [[5]]  
  "335": [[6]]  
  "1600": [[7]]  
  "1700": [[8]]  
  AIA: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]  
  EUVI: [[2, 3, 4, 5]] 
  EUI: [[2, 5]] 
  SUVI: [[0, 1, 2, 3, 4, 5]]  
  CIRCE: [[1, 3, 5]]

# Training logging
wandb:
  entity: 'tremblaybenoit'  # Name of wandb entity
  project: 'megs-ai'  # Name of wandb project
  group: 'Virtual Instrumentation'  # Name of wandb group
  job_type: 'Training'  # Nme of wandb job_type
  tags: ['development'] # Run tags
  notes: "Training for different combination of wavelengths corresponding to EUV-observing instruments."
